"""DLA PUB LOG ingestion via the FLIS Electronic Reading Room CSV feeds.

The Reading Room replaced the legacy flat-file feed in April 2023. Each topic
ships as a zip of standard RFC 4180 CSVs, one CSV per logical table. Monthly
files are republished on the first business day of each month; quarterly
files (FLISV, MRD) are republished quarterly.

DLA's CDN (Akamai Bot Manager) rejects curl/wget/Schannel TLS fingerprints
outright. Python `requests` happens to slip through with a recent Chrome
User-Agent; do NOT "clean up" the UA below without testing against the live
endpoint, or ingest will silently 403.
"""
import csv
import os
import zipfile
from typing import Any, Dict, Iterator, List, Optional

import dlt
import requests

PUBLOG_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/148.0.0.0 Safari/537.36"
)

PUBLOG_BASE_URL = (
    "https://www.dla.mil/Portals/104/Documents/"
    "InformationOperations/LogisticsInformationServices/FOIA/PUBLOG/"
)

PUBLOG_FOIA_BASE_URL = (
    "https://www.dla.mil/Portals/104/Documents/"
    "InformationOperations/LogisticsInformationServices/FOIA/"
)

PUBLOG_MONTHLY_URLS: List[str] = [
    PUBLOG_BASE_URL + name
    for name in (
        "CAGE.zip",
        "CHARACTERISTICS.zip",
        "FREIGHT_PACKAGING.zip",
        "HISTORY.zip",
        "H-SERIES.zip",
        "IDENTIFICATION.zip",
        "MANAGEMENT.zip",
        "REFERENCE.zip",
        "MOE_RULE.zip",
    )
]

PUBLOG_QUARTERLY_URLS: List[str] = [
    # FLISV_1.zip 404s (DLA serves that as HTTP 200 text/html, so it fails late
    # and confusingly). The live file is FLISV.zip, and its `ver` query param is
    # load-bearing -- without it the portal returns the 404 page.
    PUBLOG_BASE_URL + "FLISV.zip?ver=8lwvL-2fQoC8fQloktcenw%3d%3d",
    PUBLOG_FOIA_BASE_URL + "MRD0107.CSV",
    PUBLOG_FOIA_BASE_URL + "MRD0300.CSV",
    PUBLOG_FOIA_BASE_URL + "MRD0500.CSV",
    PUBLOG_FOIA_BASE_URL + "MRD06P1.CSV",
    PUBLOG_FOIA_BASE_URL + "MRD06P2.CSV",
]

# CSV members of each source file, keyed by the source's filename.
#
# Dagster needs asset keys at definition time, but a zip's members are only
# knowable after downloading it -- so the mapping is checked in here rather
# than discovered. Generated by reading each zip's central directory over HTTP
# Range requests (see scripts/discover_manifest.py) and verified against a live
# run's extraction counts. Ingest reconciles this against the real archive at
# runtime and warns on drift, so a stale entry degrades loudly, not silently.
PUBLOG_SOURCE_MANIFEST: Dict[str, List[str]] = {
    "CAGE.zip": [
        "P_CAGE.CSV",
        "V_CAGE_ADDRESS.CSV",
        "V_CAGE_STATUS_AND_TYPE.CSV",
    ],
    "CHARACTERISTICS.zip": [
        "V_CHARACTERISTICS.CSV",
    ],
    "FREIGHT_PACKAGING.zip": [
        "V_DSS_WEIGHT_AND_CUBE.CSV",
        "V_FLIS_PACKAGING_1.CSV",
        "V_FLIS_PACKAGING_2.CSV",
        "V_FLIS_PACKAGING_3.CSV",
        "V_FREIGHT.CSV",
    ],
    "HISTORY.zip": [
        "P_HISTORY_PICK.CSV",
        "V_ITEM_IDENTIFICATION_HISTORY.CSV",
        "V_MANAGEMENT_HISTORY.CSV",
        "V_REFERENCE_NUMBER_HISTORY.CSV",
    ],
    "H-SERIES.zip": [
        "P_H2_PICK.CSV",
        "P_H5_PICK.CSV",
        "P_H6_PICK.CSV",
        "V_FSC_IMM.CSV",
        "V_H2_FSC.CSV",
        "V_H2_FSC_INC.CSV",
        "V_H2_FSG.CSV",
        "V_H3_AMMUNITION.CSV",
        "V_H5_BUSINESS.CSV",
        "V_H5_CORPORATE.CSV",
        "V_H5_DOMESTIC.CSV",
        "V_H5_FOREIGN.CSV",
        "V_H6_MODIFIER.CSV",
        "V_H6_NAME_INC.CSV",
        "V_H6_RELATED.CSV",
    ],
    "IDENTIFICATION.zip": [
        "P_FLIS_NSN.CSV",
        "P_HELP.CSV",
        "V_COLLOQUIAL_NAME.CSV",
        "V_FLIS_CANCELLED_NIIN.CSV",
        "V_FLIS_IDENTIFICATION.CSV",
        "V_FLIS_STANDARDIZATION.CSV",
    ],
    "MANAGEMENT.zip": [
        "V_FLIS_MANAGEMENT.CSV",
        "V_FLIS_MANAGEMENT_FUTURE.CSV",
        "V_FLIS_PHRASE.CSV",
        "V_MGMT_AIR_FORCE.CSV",
        "V_MGMT_ARMY.CSV",
        "V_MGMT_COAST_GUARD.CSV",
        "V_MGMT_MARINE_CORPS.CSV",
        "V_MGMT_NAVY.CSV",
        "V_SOCOM_MANAGEMENT.CSV",
    ],
    "REFERENCE.zip": [
        "V_FLIS_PART.CSV",
    ],
    "MOE_RULE.zip": [
        "V_MOE_RULE.CSV",
    ],
    # One 2.25 GiB CSV in a 385 MiB archive -- by far the largest single table,
    # and unsplittable, so its asset dominates quarterly wall-clock on its own.
    "FLISV.zip": [
        "FLISV.CSV",
    ],
    # Bare CSVs are their own single member.
    "MRD0107.CSV": ["MRD0107.CSV"],
    "MRD0300.CSV": ["MRD0300.CSV"],
    "MRD0500.CSV": ["MRD0500.CSV"],
    "MRD06P1.CSV": ["MRD06P1.CSV"],
    "MRD06P2.CSV": ["MRD06P2.CSV"],
}


def source_filename(url: str) -> str:
    """Filename for a source URL, ignoring any query string or fragment.

    DLA's portal appends a cache-busting `?ver=...` to some links, and that
    param is required -- so it cannot simply be stripped from the URL. Every
    place that derives a name from the URL must go through this instead of
    splitting on `/`, or it sees `FLISV.zip?ver=8lwvL...` as the filename and
    fails the `.zip` suffix check, the manifest lookup, and the slug.
    """
    return url.split("#", 1)[0].split("?", 1)[0].rsplit("/", 1)[-1]


def table_name_for(csv_member: str) -> str:
    """dlt table name for a CSV member: `V_CAGE_ADDRESS.CSV` -> `v_cage_address`.

    Must stay in agreement with the table naming in `publog_csv_resource`.
    """
    return os.path.splitext(os.path.basename(csv_member))[0].lower()


def manifest_tables(url: str) -> List[str]:
    """Declared dlt table names for a source URL, in manifest order."""
    filename = source_filename(url)
    if filename not in PUBLOG_SOURCE_MANIFEST:
        raise KeyError(
            f"No PUBLOG_SOURCE_MANIFEST entry for {filename!r}. Add its CSV "
            f"members to pub_tools/assets.py so per-table assets can be declared."
        )
    return [table_name_for(m) for m in PUBLOG_SOURCE_MANIFEST[filename]]


def publog_session() -> requests.Session:
    s = requests.Session()
    s.headers.update({"User-Agent": PUBLOG_USER_AGENT})
    return s


def _reject_error_page(url: str, response: requests.Response) -> None:
    """Raise if the CDN served an HTML error page as a 200.

    DLA's portal returns its 404 page with HTTP 200 and Content-Type text/html
    for missing files, so `raise_for_status()` sees nothing wrong and the
    failure surfaces much later as a confusing BadZipFile or a CSV of markup.
    """
    content_type = (response.headers.get("Content-Type") or "").lower()
    if "text/html" in content_type:
        raise RuntimeError(
            f"{url} returned an HTML page (Content-Type: {content_type}), not a "
            f"data file -- DLA serves its 404 page as HTTP 200. The file has "
            f"most likely been moved or withdrawn."
        )


def fetch_last_modified(session: requests.Session, url: str) -> Optional[str]:
    """Return the Last-Modified header for url, or None if absent.

    Akamai blocks HEAD on these URLs, so we issue a GET with stream=True and
    close immediately after reading the headers.
    """
    with session.get(url, stream=True, timeout=30) as r:
        r.raise_for_status()
        _reject_error_page(url, r)
        return r.headers.get("Last-Modified")


def download_url(session: requests.Session, url: str, dest_path: str) -> None:
    """Stream a URL to dest_path."""
    with session.get(url, stream=True, timeout=600) as r:
        r.raise_for_status()
        _reject_error_page(url, r)
        with open(dest_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    f.write(chunk)


def fetch_url_to_dir(session: requests.Session, url: str, dest_dir: str) -> List[str]:
    """Download url into dest_dir. If it's a zip, extract and return the list
    of contained CSV paths. If it's a bare CSV, return [downloaded path].
    """
    os.makedirs(dest_dir, exist_ok=True)
    filename = source_filename(url)
    local_path = os.path.join(dest_dir, filename)
    download_url(session, url, local_path)

    if filename.lower().endswith(".zip"):
        with zipfile.ZipFile(local_path) as z:
            z.extractall(dest_dir)
            csvs = [
                os.path.join(dest_dir, n)
                for n in z.namelist()
                if n.lower().endswith(".csv") and not n.endswith("/")
            ]
        os.remove(local_path)
        return csvs

    if filename.lower().endswith(".csv"):
        return [local_path]

    raise ValueError(f"Unsupported PUB LOG file type for url: {url}")


def _clean_header(s: str) -> str:
    return (
        s.strip()
        .replace(" ", "_")
        .replace(".", "_")
        .replace("-", "_")
        .replace("/", "_")
        .lower()
    )


@dlt.resource(name="publog_table", write_disposition="replace")
def publog_csv_resource(
    csv_paths: List[str],
    log: Optional[Any] = None,
    row_counts: Optional[Dict[str, int]] = None,
    progress_every: int = 250_000,
) -> Iterator[dict]:
    """Stream rows from each CSV, routing to a dlt table named after the file.

    The dlt load is by far the longest phase of ingest and emits no output of
    its own, so an unprogressed run is indistinguishable from a hung one. Pass
    `log` (a Dagster logger) to get a line per file plus a heartbeat every
    `progress_every` rows, and `row_counts` (a dict this mutates in place) to
    recover per-table totals for materialization metadata.
    """
    for i, csv_path in enumerate(csv_paths, start=1):
        table_name = os.path.splitext(os.path.basename(csv_path))[0].lower()
        size_mb = os.path.getsize(csv_path) / (1024 * 1024)
        if log:
            log.info(
                "[%d/%d] reading %s (%.1f MiB) -> table %s",
                i, len(csv_paths), os.path.basename(csv_path), size_mb, table_name,
            )
        rows = 0
        with open(csv_path, "r", encoding="utf-8", errors="replace", newline="") as f:
            reader = csv.reader(f)
            try:
                raw_headers = next(reader)
            except StopIteration:
                if log:
                    log.warning("[%d/%d] %s is empty; skipping", i, len(csv_paths), table_name)
                continue
            headers = [_clean_header(h) for h in raw_headers]
            for row in reader:
                if len(row) < len(headers):
                    row = row + [""] * (len(headers) - len(row))
                elif len(row) > len(headers):
                    row = row[: len(headers)]
                record = dict(zip(headers, row))
                rows += 1
                if log and rows % progress_every == 0:
                    log.info("[%d/%d] %s: %s rows read...", i, len(csv_paths), table_name, f"{rows:,}")
                yield dlt.mark.with_table_name(record, table_name)
        if row_counts is not None:
            row_counts[table_name] = rows
        if log:
            log.info("[%d/%d] %s: %s rows read", i, len(csv_paths), table_name, f"{rows:,}")


def load_previous_last_modified(
    context,
    asset_key=None,
    metadata_key: str = "source_last_modified",
) -> Dict[str, str]:
    """Read the per-url Last-Modified map from the latest materialization of
    `asset_key`. Returns {} if none recorded or unparseable.

    `asset_key` must be passed from a multi_asset, where `context.asset_key` is
    ambiguous; it defaults to the running asset for single-asset callers.
    """
    key = asset_key if asset_key is not None else context.asset_key
    try:
        event = context.instance.get_latest_materialization_event(key)
    except Exception:
        return {}
    if event is None or event.asset_materialization is None:
        return {}
    meta = event.asset_materialization.metadata.get(metadata_key)
    if meta is None:
        return {}
    for attr in ("data", "value"):
        if hasattr(meta, attr):
            try:
                return dict(getattr(meta, attr))
            except (TypeError, ValueError):
                pass
    if hasattr(meta, "text"):
        import json
        try:
            return json.loads(meta.text)
        except (TypeError, ValueError):
            return {}
    try:
        return dict(meta)
    except (TypeError, ValueError):
        return {}
